# encoding: UTF-8

control 'C-5.9' do
  title 'Ensure Audit Logging is Enabled'
  desc  "
    To manage your enterprise caching solution, it is important that you know how your clusters are performing and the resources they are consuming. It's also important that you know the events that are being generated and the costs of your deployment.

    Amazon CloudWatch provides metrics for monitoring your cache performance. In addition, cost allocation tags help you monitor and manage costs.
  "
  desc  'rationale', "
    To manage your enterprise caching solution, it is important that you know how your clusters are performing and the resources they are consuming. It's also important that you know the events that are being generated and the costs of your deployment.

    Amazon CloudWatch provides metrics for monitoring your cache performance. In addition, cost allocation tags help you monitor and manage costs.
  "
  desc  'check', "
    1. Sign in to the AWS Management Console
    - Sign in to the AWS Management Console at https://console.aws.amazon.com/ with your AWS account credentials.

    2. Open the Amazon Keyspaces Console
    - Navigate to the service using the `Find Services` search bar or by directly accessing the console at https://console.aws.amazon.com/keyspaces/.

    3. Select the Keyspace
    - Choose the Keyspace (database) for which you want to enable audit logging.
    - Click on the Keyspace name to access its details page.

    4. Enable Amazon CloudWatch Logs
    - In the Keyspace details page, click on the `Configuration` tab.
    - Under the `Logging` section, locate the `CloudWatch Logs` option.
    - Click on `Edit`.
    - Select the `Enable` option to enable logging for the Keyspace.
    - Choose an existing CloudWatch Logs log group or create a new one to store the logs generated by the Keyspace activities.
    - Click `Save` to enable CloudWatch Logs for the Keyspace.

    5. Configure CloudWatch Logs
    - Open the CloudWatch console by navigating to `CloudWatch` in the AWS Management Console.
    - In the left-side menu, click on `Logs`.
    - Create a new log group or select an existing log group that will store the Keyspaces logs.
    - Configure log retention settings based on your retention requirements. Logs can be stored for a specific number of days or indefinitely.
    - Define any necessary log group permissions to control access to the logs.
    - Optionally, set up log exports or alarms for specific log events or patterns if needed.

    6. Verify the Logging Status
    - Wait a few minutes for the changes to propagate and the logging configuration to take effect.
    - Refresh the Keyspace details page to see the updated logging status.
    - Verify that CloudWatch Logs is enabled for the Keyspace.

    7. Monitor and Analyze Logs
    - Navigate to the CloudWatch console and select the log group that stores the Keyspaces logs.
    - Monitor the logs to gain insights into the activities and operations performed on your Keyspace.
    - Use CloudWatch Logs features, such as log searching, filtering, and visualization, to analyze the logs and identify any security or operational issues.
    - Establish appropriate log monitoring and alerting mechanisms to proactively identify and respond to potential security incidents or operational anomalies.
  "
  desc  'fix', "
    TODO: fix text missing in source XCCDF
  "
  tag severity:              'medium'
  tag nist:                  ['AC-2 f', 'AU-1 a 1 (a)']
  tag cci:                   ['CCI-000011', 'CCI-000117']
  tag cis_number:            '5.9'
  tag cis_rid:               '5.9'
  tag cis_benchmark:         'CIS AWS Database Services Benchmark v2.0.0'
  tag cis_rule_id:           'SV-0509r1_rule'
  tag cis_version:           '2.0.0'
  tag cis_level:             1
  tag cis_scored:            true
  tag applicable_partitions: ['aws', 'aws-us-gov']
  tag implementation_status: 'implemented'
  tag exec_validated:        false

  applicable_partition = ['aws', 'aws-us-gov'].include?(input('aws_partition'))
  applicable_service   = Array(input('applicable_services')).empty? || Array(input('applicable_services')).include?('elasticache')
  # Hoisted so an EMPTY collection is a declared state rather than an absent one.
  # The service can be in scope while the account holds none of the resource: the
  # loop below then never executed, the control registered no describe blocks, and
  # it emitted ZERO results — neither passed nor Not Applicable, just absent. A
  # control that asserts nothing while reporting not-red is the failure this
  # profile exists to catch, and it also fails `hdf convert`, whose schema requires
  # at least one result per requirement.
  scoped_items = aws_elasticache_clusters.ids
  applicable           = applicable_partition && applicable_service && !scoped_items.empty?

  impact 0.5
  impact 0.0 unless applicable

  only_if("ELASTICACHE out of scope (partition=#{input('aws_partition')}, applicable_services=#{input('applicable_services')}) or none present in this account") do
    applicable
  end

  scoped_items.each do |id|
    describe aws_elasticache_cluster(cache_cluster_id: id) do
      its('log_delivery_configurations') { should_not be_empty }
    end
  end
end
