# encoding: UTF-8

control 'C-6.4' do
  title 'Ensure Audit Logging is Enabled'
  desc  "
    Enabling audit logging on Amazon MemoryDB allows you to capture and store logs of activities performed on your clusters.

    It captures and saves logs of activities that took place in the cluster.
  "
  desc  'rationale', "
    Enabling audit logging on Amazon MemoryDB allows you to capture and store logs of activities performed on your clusters.

    It captures and saves logs of activities that took place in the cluster.
  "
  desc  'check', "
    1. Sign into the AWS Management Console 
    - Sign into the AWS Management Console at https://console.aws.amazon.com/ with your AWS account credentials.

    2. Open the Amazon MemoryDB Console 
    - Navigate to the service using the `Find Services` search bar or by directly accessing the console at https://console.aws.amazon.com/memorydb/.

    3. Select the Cluster 
    - Choose the MemoryDB cluster for which you want to enable audit logging. Click on the cluster name to access its details page.

    4. Enable Amazon CloudWatch Logs
    - In the cluster details page, navigate to the `Logging` section.
    - Click on `Modify` to edit the logging settings.
    - Select the option to enable CloudWatch Logs.
    - Choose an existing CloudWatch log group or create a new one to store the logs generated by the MemoryDB cluster activities.
    - Optionally, you can specify a log retention period to define how long the logs will be stored.
    - Click `Apply Changes` to enable CloudWatch Logs for the MemoryDB cluster.

    5. Configure CloudWatch Logs
    - Open the CloudWatch console by navigating to `CloudWatch` in the AWS Management Console.
    - In the left-side menu, click on `Logs`.
    - Create a new log group or select an existing log group that will store the MemoryDB logs.
    - Configure log retention settings based on your retention requirements. Logs can be stored for a specific number of days or indefinitely.
    - Define any necessary log group permissions to control access to the logs.
    - Optionally, set up log exports or alarms for specific log events or patterns if needed.

    6. Verify Logging Status
    - Wait a few minutes for the changes to propagate and the logging configuration to take effect.
    - Refresh the cluster details page to see the updated logging status.
    - Verify that CloudWatch Logs is enabled for the MemoryDB cluster.

    7. Monitor and Analyze Logs
    - Navigate to the CloudWatch console and select the log group that stores the MemoryDB logs.
    - Monitor the logs to gain insights into the activities and operations performed on your MemoryDB cluster.
    - Use CloudWatch Logs features, such as log searching, filtering, and visualization, to analyze the logs and identify any security or operational issues.
    - Establish appropriate log monitoring and alerting mechanisms to proactively identify and respond to potential security incidents or operational anomalies.
  "
  desc  'fix', "
    TODO: fix text missing in source XCCDF
  "
  tag severity:              'medium'
  tag nist:                  ['AC-2 f', 'AU-1 a 1 (a)']
  tag cci:                   ['CCI-000011', 'CCI-000117']
  tag cis_number:            '6.4'
  tag cis_rid:               '6.4'
  tag cis_benchmark:         'CIS AWS Database Services Benchmark v2.0.0'
  tag cis_rule_id:           'SV-0604r1_rule'
  tag cis_version:           '2.0.0'
  tag cis_level:             1
  tag cis_scored:            true
  tag applicable_partitions: ['aws', 'aws-us-gov']
  tag implementation_status: 'implemented'
  tag exec_validated:        false

  applicable_partition = ['aws', 'aws-us-gov'].include?(input('aws_partition'))
  applicable_service   = Array(input('applicable_services')).empty? || Array(input('applicable_services')).include?('memorydb')
  applicable           = applicable_partition && applicable_service

  impact 0.5
  impact 0.0 unless applicable

  only_if("MEMORYDB out of scope (partition=#{input('aws_partition')}, applicable_services=#{input('applicable_services')})") do
    applicable
  end

  inv = aws_memorydb_compliance(regions: input('scan_regions'))
  if inv.connection_error
    describe 'AWS MemoryDB inventory' do
      skip "Requires manual review and attestation provided for this control (#{inv.connection_error})"
    end
  else
    describe inv do
      its('clusters_without_audit_logging') { should be_empty }
    end
  end
end
