# encoding: UTF-8

control 'C-7.6' do
  title 'Ensure Audit Logging is Enabled'
  desc  "
    Enable audit logging to capture database activities, including login attempts, queries, and modifications. Send the logs to Amazon CloudWatch or a centralized log management system for analysis and monitoring.

    It captures and saves logs of activities that took place in the cluster, by recording login attempts, queries, and any changes within the database.
  "
  desc  'rationale', "
    Enable audit logging to capture database activities, including login attempts, queries, and modifications. Send the logs to Amazon CloudWatch or a centralized log management system for analysis and monitoring.

    It captures and saves logs of activities that took place in the cluster, by recording login attempts, queries, and any changes within the database.
  "
  desc  'check', "
    1. Sign into the AWS Management Console
    - Sign into the AWS Management Console at https://console.aws.amazon.com/ with your AWS account credentials.

    2. Open the Amazon DocumentDB Console
    - Navigate to the service using the `Find Services` search bar or by directly accessing the console at https://console.aws.amazon.com/docdb/.

    3. Select the DocumentDB Cluster
    - Choose the Amazon DocumentDB cluster for which you want to enable audit logging. 
    - Click on the cluster name to access its details page.
    - In the cluster details page, navigate to the \"Configuration\" section.

    4. Enable Audit Logging
    - Under the `Database options` or `Database features` section.
    - Click on the `Edit` button or `Modify` option to configure the audit logging settings.
    - Enable the option for audit logging by choosing the appropriate setting.
    - Specify the destination for the audit logs, which can be an Amazon CloudWatch Logs group or an Amazon S3 bucket.

    5. Configure Audit Log Destination
    - If you choose to send audit logs to an Amazon CloudWatch Logs group, select the existing group or create a new one.
    - If you choose to send audit logs to an Amazon S3 bucket, select the existing bucket or create a new one. Provide the necessary permissions for DocumentDB to write logs to the bucket.

    6. Set Audit Log Retention Period
    - Specify the retention period for the audit logs, indicating how long the logs should be retained in the selected destination.
    - Consider your compliance and regulatory requirements when determining the retention period.

    7. Save the Configuration
    Click on the `Save` button to apply the audit logging configuration.
    DocumentDB will start recording audit logs according to the configured settings.

    8. Validate Audit Logging
    - Perform operations on your DocumentDB cluster to generate audit log events.
    - Verify that the audit logs are recorded and sent to the specified destination.
    - Review the logs to ensure they contain the expected information and events.

    9. Monitor and Analyze Audit Logs
    - Use Amazon CloudWatch Logs or other log analysis tools to monitor and analyze the audit logs generated by DocumentDB.
    - Set up log metrics, alarms, and notifications to detect unusual activities or security incidents.
    - Review audit logs regularly to identify potential security threats, compliance violations, or unauthorized access attempts.
  "
  desc  'fix', "
        ```
        aws docdb modify-db-cluster --db-cluster-identifier <cluster-id> --cloudwatch-logs-export-configuration '{\"EnableLogTypes\":[\"audit\",\"profiler\"]}' --apply-immediately
        ```

    1. Enable the `audit_logs` cluster parameter as well - exporting alone produces
       nothing if auditing is off at the engine.
    2. Choose the event categories deliberately; auditing every read on a busy
       cluster produces volume that obscures rather than informs.
    3. Set retention on the log group and confirm records arrive.
  "
  tag severity:              'medium'
  tag severity_source:       'unassessed'
  tag nist:                  ['AC-2 f', 'AU-1 a 1 (a)']
  tag nist_r4:               ['AC-2 f', 'AU-1 a 1']
  tag cci:                   ['CCI-000011', 'CCI-000117']
  tag cis_number:            '7.6'
  tag cis_rid:               '7.6'
  tag cis_benchmark:         'CIS AWS Database Services Benchmark v2.0.0'
  tag cis_rule_id:           'SV-0706r1_rule'
  tag cis_version:           '2.0.0'
  tag cis_level:             1
  tag cis_scored:            true
  tag applicable_partitions: ['aws', 'aws-us-gov']
  tag implementation_status: 'implemented'
  tag exec_validated:        false

  applicable_partition = ['aws', 'aws-us-gov'].include?(input('aws_partition'))
  applicable_service   = Array(input('applicable_services')).empty? || Array(input('applicable_services')).include?('documentdb')
  applicable           = applicable_partition && applicable_service

  impact 0.5
  impact 0.0 unless applicable

  only_if("DOCUMENTDB out of scope (partition=#{input('aws_partition')}, applicable_services=#{input('applicable_services')})") do
    applicable
  end

  describe aws_rds_cluster_compliance(regions: input('scan_regions'), engines: ['docdb']) do
    its('clusters_without_audit_logging') { should be_empty }
  end
end
