# encoding: UTF-8

control 'C-9.5' do
  title 'Ensure Audit Logging is Enabled'
  desc  "
    This control is important because it helps ensure activity within the cluster and identifies who has last modified the document and who has access to it, in case of breaches. It also ensures compliance with regulation requirements.
  "
  desc  'rationale', "
    This control is important because it helps ensure activity within the cluster and identifies who has last modified the document and who has access to it, in case of breaches. It also ensures compliance with regulation requirements.
  "
  desc  'check', "
    1. Sign into the AWS Management Console 
    - Sign into the AWS Management Console at https://console.aws.amazon.com/ with your AWS account credentials.

    2. Open the Amazon Neptune Console 
    - Navigate to the service using the `Find Services` search bar or by directly accessing the console at https://console.aws.amazon.com/neptune/.

    3. Select the Neptune Cluster 
    - Choose the Amazon Neptune cluster on which you want to enable audit logging. Click on the cluster name to access its details page.

    4. Enable Amazon CloudWatch Logs
    - In the cluster details page, navigate to the `Monitoring` or `Logging` section.
    - Under `CloudWatch Logs`, click `Enable` to enable logging for the Neptune cluster.
    - Select an existing CloudWatch Logs group or create a new one to store the logs.
    - Choose the appropriate retention period for the logs, considering your compliance and retention requirements.
    - Click `Save` or `Apply Changes` to enable CloudWatch Logs for the Neptune cluster.

    5. Configure Log Levels (Optional)
    - In the cluster details page, navigate to the `Configuration` or `Logging` section.
    - Under `Logging`, you may have the option to configure log levels for different components of Neptune, such as query logs or error logs.
    - Adjust the log levels according to your logging and troubleshooting needs.
    - Click `Apply Changes` to save the log level configuration.

    6. Review and Analyze Logs
    - Access the Amazon CloudWatch console by navigating to `CloudWatch` in the AWS Management Console.
    - Go to the CloudWatch Logs section and locate the log group associated with your Neptune cluster.
    - Select the log group and review the logs generated by Neptune.
    - Analyze the logs for troubleshooting, performance monitoring, or auditing purposes.

    7. Set Up Log Metric Filters and Alarms (Optional)
    - In the CloudWatch console, navigate to `Metric Filters` in the left-side menu.
    - Click on `Create metric filter` to set up filters to extract specific information from the Neptune logs.
    - Define the filter patterns to capture the desired log events and extract the required metrics.
    - Configure alarms based on the extracted metrics to trigger notifications or automated actions when specific conditions are met.

    8. Regularly Monitor Logs
    - Continuously monitor the logs generated by Neptune using the CloudWatch Logs console or programmatically using the CloudWatch APIs.
    - Review the logs regularly to identify any abnormal or suspicious activities.
    - Set up appropriate notifications or alerts to proactively respond to critical log events.
  "
  desc  'fix', "
    TODO: fix text missing in source XCCDF
  "
  tag severity:              'medium'
  tag nist:                  ['AC-2 f', 'AU-1 a 1 (a)']
  tag cci:                   ['CCI-000011', 'CCI-000117']
  tag cis_number:            '9.5'
  tag cis_rid:               '9.5'
  tag cis_benchmark:         'CIS AWS Database Services Benchmark v2.0.0'
  tag cis_rule_id:           'SV-0905r1_rule'
  tag cis_version:           '2.0.0'
  tag cis_level:             1
  tag cis_scored:            true
  tag applicable_partitions: ['aws', 'aws-us-gov']
  tag implementation_status: 'implemented'
  tag exec_validated:        false

  applicable_partition = ['aws', 'aws-us-gov'].include?(input('aws_partition'))
  applicable_service   = Array(input('applicable_services')).empty? || Array(input('applicable_services')).include?('neptune')
  applicable           = applicable_partition && applicable_service

  impact 0.5
  impact 0.0 unless applicable

  only_if("NEPTUNE out of scope (partition=#{input('aws_partition')}, applicable_services=#{input('applicable_services')})") do
    applicable
  end

  describe aws_rds_cluster_compliance(regions: input('scan_regions'), engines: ['neptune']) do
    its('clusters_without_audit_logging') { should be_empty }
  end
end
